version: "3.8"

services:
  mysql-db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./LMS/
      dockerfile: ./Dockerfile
    env_file: .env
    restart: always
    volumes:
      - django:/app/
    depends_on:
      - mysql-db
    expose:
      - 8000
    ports:
      - "8000:8000"

volumes:
  mysql_data:
  django: